### ISSUE TITLE
Project Idea

### ISSUE THREAD

**Issue by hmthomas93** [hmthomas93/MobileAppProject#1]
We need to decide what type of project we want to work on and the components involved.

At least two of these components are needed:
- Map
- UIWebView
- UIImagePickerView
- Remote Web Services

Please list some ideas for the overall project and what components you would _like_ to use and which you would _not like_ to use.

:+1:

**Comment by hmthomas93** [comment]
Component Preferences:
- Any

Ideas:
- Upload photos for a location so other users can view the pictures associated with the location or add to the existing photos for the location (web services, map, image picker).
- Have users write reviews about locations on a map with other users being able to view the reviews (map, web services).
- Have users comment on pictures that other users have uploaded - maybe like instagram with a theme (web services, image picker).

Can't wait to hear your ideas!

**Comment by SumnerVanSchoyck** [comment]
Component preferences: Maps and UIImagePickerView (since we already know how to do both of these). I'm neutral on Web View (it's probably similar to Map View), but I don't know anything about using web services, so I'd like to avoid that if possible.

I don't know what everyone had in mind for storing data, but as long as it's OK for the project, I'd like to stick to just using Core Data for persistent data storage (no remote database/server storage).

For the app, how about a travel-oriented social networking app where users can log in and post their pictures and share where they were taken? Other users could then comment on these pictures and view the location on a map. Each user could have their own page where they would see their posts/photos and all the comments in response to them. Also, we could have a "Places I've Been" feature that shows a wide view map with pins on every location a user has posted. A user could also "Friend" other users, and then quickly view their pages through a friend list. This idea would use both Maps and UIImagePickerView, and it would also have multi-user functionality (login, user profiles, etc.).
